In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dfr = pd.read_csv(r"C:\Users\Saniya Mirza\Desktop\Pandas\review - 1.csv")

In [4]:
dfr

    age  gender education   review
0    30  Female    School  Average
1    68  Female        UG     Poor
2    70  Female        PG     Good
3    72  Female        PG     Good
4    16  Female        UG  Average
5    31  Female    School  Average
6    18    Male    School     Good
7    60  Female    School     Poor
8    65  Female        UG  Average
9    74    Male        UG     Good
10   98  Female        UG     Good
11   74    Male        UG     Good
12   51    Male    School     Poor
13   57  Female    School  Average
14   15    Male        PG     Poor
15   75    Male        UG     Poor
16   59    Male        UG     Poor
17   22  Female        UG     Poor
18   19    Male    School     Good
19   97    Male        PG     Poor
20   57  Female    School  Average
21   32    Male        PG  Average
22   18  Female        PG     Poor
23   96  Female    School     Good
24   16  Female        PG  Average
25   57  Female    School     Good
26   53  Female        PG     Poor
27   69  Female        PG     Poor
28   48    Male    School     Poor
29   83  Female        UG  Average
30   73    Male        UG  Average
31   22  Female    School     Poor
32   92    Male        UG  Average
33   89  Female        PG     Good
34   86    Male    School  Average
35   74    Male    School     Poor
36   34  Female        UG     Good
37   94    Male        PG  Average
38   45  Female    School     Good
39   76    Male        PG     Poor
40   39    Male    School     Good
41   23    Male        PG     Good
42   30  Female        PG     Good
43   27    Male        PG     Poor
44   77  Female        UG  Average
45   61    Male        PG     Poor
46   64  Female        PG     Poor
47   38  Female        PG     Good
48   39  Female        UG     Good
49   25  Female        UG     Good

In [5]:
dfr["education"].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [6]:
dfr["review"].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [7]:
dfr[["gender"]]

    gender
0   Female
1   Female
2   Female
3   Female
4   Female
5   Female
6     Male
7   Female
8   Female
9     Male
10  Female
11    Male
12    Male
13  Female
14    Male
15    Male
16    Male
17  Female
18    Male
19    Male
20  Female
21    Male
22  Female
23  Female
24  Female
25  Female
26  Female
27  Female
28    Male
29  Female
30    Male
31  Female
32    Male
33  Female
34    Male
35    Male
36  Female
37    Male
38  Female
39    Male
40    Male
41    Male
42  Female
43    Male
44  Female
45    Male
46  Female
47  Female
48  Female
49  Female

### One Hot Encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe = OneHotEncoder()

In [10]:
ohe

OneHotEncoder()

In [11]:
ohe.fit(dfr[["gender"]])

OneHotEncoder()

In [12]:
ohe.transform(dfr[["gender"]])

<50x2 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [13]:
ohe.transform(dfr[["gender"]]).toarray()

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [14]:
ary1 = ohe.transform(dfr[["gender"]]).toarray()

In [15]:
ary1

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [16]:
pd.DataFrame(ary1,dtype = "int")

    0  1
0   1  0
1   1  0
2   1  0
3   1  0
4   1  0
5   1  0
6   0  1
7   1  0
8   1  0
9   0  1
10  1  0
11  0  1
12  0  1
13  1  0
14  0  1
15  0  1
16  0  1
17  1  0
18  0  1
19  0  1
20  1  0
21  0  1
22  1  0
23  1  0
24  1  0
25  1  0
26  1  0
27  1  0
28  0  1
29  1  0
30  0  1
31  1  0
32  0  1
33  1  0
34  0  1
35  0  1
36  1  0
37  0  1
38  1  0
39  0  1
40  0  1
41  0  1
42  1  0
43  0  1
44  1  0
45  0  1
46  1  0
47  1  0
48  1  0
49  1  0

In [17]:
ohe.categories_

[array(['Female', 'Male'], dtype=object)]

In [18]:
pd.DataFrame(ary1 , dtype = "int" , columns = ['Female', 'Male'])

    Female  Male
0        1     0
1        1     0
2        1     0
3        1     0
4        1     0
5        1     0
6        0     1
7        1     0
8        1     0
9        0     1
10       1     0
11       0     1
12       0     1
13       1     0
14       0     1
15       0     1
16       0     1
17       1     0
18       0     1
19       0     1
20       1     0
21       0     1
22       1     0
23       1     0
24       1     0
25       1     0
26       1     0
27       1     0
28       0     1
29       1     0
30       0     1
31       1     0
32       0     1
33       1     0
34       0     1
35       0     1
36       1     0
37       0     1
38       1     0
39       0     1
40       0     1
41       0     1
42       1     0
43       0     1
44       1     0
45       0     1
46       1     0
47       1     0
48       1     0
49       1     0

In [19]:
dfen = pd.DataFrame(ary1 , dtype = "int" , columns = ['Female', 'Male'])

In [20]:
dfen

    Female  Male
0        1     0
1        1     0
2        1     0
3        1     0
4        1     0
5        1     0
6        0     1
7        1     0
8        1     0
9        0     1
10       1     0
11       0     1
12       0     1
13       1     0
14       0     1
15       0     1
16       0     1
17       1     0
18       0     1
19       0     1
20       1     0
21       0     1
22       1     0
23       1     0
24       1     0
25       1     0
26       1     0
27       1     0
28       0     1
29       1     0
30       0     1
31       1     0
32       0     1
33       1     0
34       0     1
35       0     1
36       1     0
37       0     1
38       1     0
39       0     1
40       0     1
41       0     1
42       1     0
43       0     1
44       1     0
45       0     1
46       1     0
47       1     0
48       1     0
49       1     0

In [21]:
df = pd.concat([dfr,dfen],axis = 1)

In [22]:
df

    age  gender education   review  Female  Male
0    30  Female    School  Average       1     0
1    68  Female        UG     Poor       1     0
2    70  Female        PG     Good       1     0
3    72  Female        PG     Good       1     0
4    16  Female        UG  Average       1     0
5    31  Female    School  Average       1     0
6    18    Male    School     Good       0     1
7    60  Female    School     Poor       1     0
8    65  Female        UG  Average       1     0
9    74    Male        UG     Good       0     1
10   98  Female        UG     Good       1     0
11   74    Male        UG     Good       0     1
12   51    Male    School     Poor       0     1
13   57  Female    School  Average       1     0
14   15    Male        PG     Poor       0     1
15   75    Male        UG     Poor       0     1
16   59    Male        UG     Poor       0     1
17   22  Female        UG     Poor       1     0
18   19    Male    School     Good       0     1
19   97    Male        PG     Poor       0     1
20   57  Female    School  Average       1     0
21   32    Male        PG  Average       0     1
22   18  Female        PG     Poor       1     0
23   96  Female    School     Good       1     0
24   16  Female        PG  Average       1     0
25   57  Female    School     Good       1     0
26   53  Female        PG     Poor       1     0
27   69  Female        PG     Poor       1     0
28   48    Male    School     Poor       0     1
29   83  Female        UG  Average       1     0
30   73    Male        UG  Average       0     1
31   22  Female    School     Poor       1     0
32   92    Male        UG  Average       0     1
33   89  Female        PG     Good       1     0
34   86    Male    School  Average       0     1
35   74    Male    School     Poor       0     1
36   34  Female        UG     Good       1     0
37   94    Male        PG  Average       0     1
38   45  Female    School     Good       1     0
39   76    Male        PG     Poor       0     1
40   39    Male    School     Good       0     1
41   23    Male        PG     Good       0     1
42   30  Female        PG     Good       1     0
43   27    Male        PG     Poor       0     1
44   77  Female        UG  Average       1     0
45   61    Male        PG     Poor       0     1
46   64  Female        PG     Poor       1     0
47   38  Female        PG     Good       1     0
48   39  Female        UG     Good       1     0
49   25  Female        UG     Good       1     0

### Ordinal Encoding

In [23]:
from sklearn.preprocessing import OrdinalEncoder

In [24]:
ord = OrdinalEncoder()

In [25]:
ord

OrdinalEncoder()

In [26]:
ord.fit(dfr[["education"]])

OrdinalEncoder()

In [27]:
ord.transform(dfr[["education"]])

array([[1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.]])

In [28]:
ord.categories_

[array(['PG', 'School', 'UG'], dtype=object)]

In [29]:
ary2 = ord.transform(dfr[["education"]])

In [30]:
ary2

array([[1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.]])

In [31]:
df["education"] = ary2.astype("int")

In [32]:
df

    age  gender  education   review  Female  Male
0    30  Female          1  Average       1     0
1    68  Female          2     Poor       1     0
2    70  Female          0     Good       1     0
3    72  Female          0     Good       1     0
4    16  Female          2  Average       1     0
5    31  Female          1  Average       1     0
6    18    Male          1     Good       0     1
7    60  Female          1     Poor       1     0
8    65  Female          2  Average       1     0
9    74    Male          2     Good       0     1
10   98  Female          2     Good       1     0
11   74    Male          2     Good       0     1
12   51    Male          1     Poor       0     1
13   57  Female          1  Average       1     0
14   15    Male          0     Poor       0     1
15   75    Male          2     Poor       0     1
16   59    Male          2     Poor       0     1
17   22  Female          2     Poor       1     0
18   19    Male          1     Good       0     1
19   97    Male          0     Poor       0     1
20   57  Female          1  Average       1     0
21   32    Male          0  Average       0     1
22   18  Female          0     Poor       1     0
23   96  Female          1     Good       1     0
24   16  Female          0  Average       1     0
25   57  Female          1     Good       1     0
26   53  Female          0     Poor       1     0
27   69  Female          0     Poor       1     0
28   48    Male          1     Poor       0     1
29   83  Female          2  Average       1     0
30   73    Male          2  Average       0     1
31   22  Female          1     Poor       1     0
32   92    Male          2  Average       0     1
33   89  Female          0     Good       1     0
34   86    Male          1  Average       0     1
35   74    Male          1     Poor       0     1
36   34  Female          2     Good       1     0
37   94    Male          0  Average       0     1
38   45  Female          1     Good       1     0
39   76    Male          0     Poor       0     1
40   39    Male          1     Good       0     1
41   23    Male          0     Good       0     1
42   30  Female          0     Good       1     0
43   27    Male          0     Poor       0     1
44   77  Female          2  Average       1     0
45   61    Male          0     Poor       0     1
46   64  Female          0     Poor       1     0
47   38  Female          0     Good       1     0
48   39  Female          2     Good       1     0
49   25  Female          2     Good       1     0

### Label Encoding

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
label = LabelEncoder()

In [35]:
label

LabelEncoder()

In [36]:
label.fit(dfr["review"])

LabelEncoder()

In [37]:
label.transform(dfr["review"])

array([0, 2, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2,
       0, 2, 2, 1, 1, 1])

In [38]:
label.classes_

array(['Average', 'Good', 'Poor'], dtype=object)

In [39]:
ary3 = label.transform(dfr["review"])

In [40]:
ary3

array([0, 2, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2,
       0, 2, 2, 1, 1, 1])

In [41]:
df["review"] = ary3

In [42]:
df

    age  gender  education  review  Female  Male
0    30  Female          1       0       1     0
1    68  Female          2       2       1     0
2    70  Female          0       1       1     0
3    72  Female          0       1       1     0
4    16  Female          2       0       1     0
5    31  Female          1       0       1     0
6    18    Male          1       1       0     1
7    60  Female          1       2       1     0
8    65  Female          2       0       1     0
9    74    Male          2       1       0     1
10   98  Female          2       1       1     0
11   74    Male          2       1       0     1
12   51    Male          1       2       0     1
13   57  Female          1       0       1     0
14   15    Male          0       2       0     1
15   75    Male          2       2       0     1
16   59    Male          2       2       0     1
17   22  Female          2       2       1     0
18   19    Male          1       1       0     1
19   97    Male          0       2       0     1
20   57  Female          1       0       1     0
21   32    Male          0       0       0     1
22   18  Female          0       2       1     0
23   96  Female          1       1       1     0
24   16  Female          0       0       1     0
25   57  Female          1       1       1     0
26   53  Female          0       2       1     0
27   69  Female          0       2       1     0
28   48    Male          1       2       0     1
29   83  Female          2       0       1     0
30   73    Male          2       0       0     1
31   22  Female          1       2       1     0
32   92    Male          2       0       0     1
33   89  Female          0       1       1     0
34   86    Male          1       0       0     1
35   74    Male          1       2       0     1
36   34  Female          2       1       1     0
37   94    Male          0       0       0     1
38   45  Female          1       1       1     0
39   76    Male          0       2       0     1
40   39    Male          1       1       0     1
41   23    Male          0       1       0     1
42   30  Female          0       1       1     0
43   27    Male          0       2       0     1
44   77  Female          2       0       1     0
45   61    Male          0       2       0     1
46   64  Female          0       2       1     0
47   38  Female          0       1       1     0
48   39  Female          2       1       1     0
49   25  Female          2       1       1     0

In [43]:
df.drop("gender",axis = 1)

    age  education  review  Female  Male
0    30          1       0       1     0
1    68          2       2       1     0
2    70          0       1       1     0
3    72          0       1       1     0
4    16          2       0       1     0
5    31          1       0       1     0
6    18          1       1       0     1
7    60          1       2       1     0
8    65          2       0       1     0
9    74          2       1       0     1
10   98          2       1       1     0
11   74          2       1       0     1
12   51          1       2       0     1
13   57          1       0       1     0
14   15          0       2       0     1
15   75          2       2       0     1
16   59          2       2       0     1
17   22          2       2       1     0
18   19          1       1       0     1
19   97          0       2       0     1
20   57          1       0       1     0
21   32          0       0       0     1
22   18          0       2       1     0
23   96          1       1       1     0
24   16          0       0       1     0
25   57          1       1       1     0
26   53          0       2       1     0
27   69          0       2       1     0
28   48          1       2       0     1
29   83          2       0       1     0
30   73          2       0       0     1
31   22          1       2       1     0
32   92          2       0       0     1
33   89          0       1       1     0
34   86          1       0       0     1
35   74          1       2       0     1
36   34          2       1       1     0
37   94          0       0       0     1
38   45          1       1       1     0
39   76          0       2       0     1
40   39          1       1       0     1
41   23          0       1       0     1
42   30          0       1       1     0
43   27          0       2       0     1
44   77          2       0       1     0
45   61          0       2       0     1
46   64          0       2       1     0
47   38          0       1       1     0
48   39          2       1       1     0
49   25          2       1       1     0

In [44]:
df.drop("gender",axis = 1 , inplace = True)

In [45]:
df

    age  education  review  Female  Male
0    30          1       0       1     0
1    68          2       2       1     0
2    70          0       1       1     0
3    72          0       1       1     0
4    16          2       0       1     0
5    31          1       0       1     0
6    18          1       1       0     1
7    60          1       2       1     0
8    65          2       0       1     0
9    74          2       1       0     1
10   98          2       1       1     0
11   74          2       1       0     1
12   51          1       2       0     1
13   57          1       0       1     0
14   15          0       2       0     1
15   75          2       2       0     1
16   59          2       2       0     1
17   22          2       2       1     0
18   19          1       1       0     1
19   97          0       2       0     1
20   57          1       0       1     0
21   32          0       0       0     1
22   18          0       2       1     0
23   96          1       1       1     0
24   16          0       0       1     0
25   57          1       1       1     0
26   53          0       2       1     0
27   69          0       2       1     0
28   48          1       2       0     1
29   83          2       0       1     0
30   73          2       0       0     1
31   22          1       2       1     0
32   92          2       0       0     1
33   89          0       1       1     0
34   86          1       0       0     1
35   74          1       2       0     1
36   34          2       1       1     0
37   94          0       0       0     1
38   45          1       1       1     0
39   76          0       2       0     1
40   39          1       1       0     1
41   23          0       1       0     1
42   30          0       1       1     0
43   27          0       2       0     1
44   77          2       0       1     0
45   61          0       2       0     1
46   64          0       2       1     0
47   38          0       1       1     0
48   39          2       1       1     0
49   25          2       1       1     0